// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikeb26/gptcli/internal/types (interfaces: GptCliAIClient)

// Package types is a generated GoMock package.
package types

import (
	context "context"
	reflect "reflect"

	openai "github.com/cloudwego/eino-ext/libs/acl/openai"
	gomock "github.com/golang/mock/gomock"
)

// MockGptCliAIClient is a mock of GptCliAIClient interface.
type MockGptCliAIClient struct {
	ctrl     *gomock.Controller
	recorder *MockGptCliAIClientMockRecorder
}

// MockGptCliAIClientMockRecorder is the mock recorder for MockGptCliAIClient.
type MockGptCliAIClientMockRecorder struct {
	mock *MockGptCliAIClient
}

// NewMockGptCliAIClient creates a new mock instance.
func NewMockGptCliAIClient(ctrl *gomock.Controller) *MockGptCliAIClient {
	mock := &MockGptCliAIClient{ctrl: ctrl}
	mock.recorder = &MockGptCliAIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGptCliAIClient) EXPECT() *MockGptCliAIClientMockRecorder {
	return m.recorder
}

// CreateChatCompletion mocks base method.
func (m *MockGptCliAIClient) CreateChatCompletion(arg0 context.Context, arg1 []*GptCliMessage) (*GptCliMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletion", arg0, arg1)
	ret0, _ := ret[0].(*GptCliMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletion indicates an expected call of CreateChatCompletion.
func (mr *MockGptCliAIClientMockRecorder) CreateChatCompletion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletion", reflect.TypeOf((*MockGptCliAIClient)(nil).CreateChatCompletion), arg0, arg1)
}

// SetReasoning mocks base method.
func (m *MockGptCliAIClient) SetReasoning(arg0 openai.ReasoningEffortLevel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReasoning", arg0)
}

// SetReasoning indicates an expected call of SetReasoning.
func (mr *MockGptCliAIClientMockRecorder) SetReasoning(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReasoning", reflect.TypeOf((*MockGptCliAIClient)(nil).SetReasoning), arg0)
}
