// Code generated by MockGen. DO NOT EDIT.
// Source: generaltypes.go

// Package types is a generated GoMock package.
package types

import (
	"context"
	"reflect"

	laclopenai "github.com/cloudwego/eino-ext/libs/acl/openai"
	"github.com/golang/mock/gomock"
)

// MockGptCliAIClient is a mock of GptCliAIClient interface.
type MockGptCliAIClient struct {
	ctrl     *gomock.Controller
	recorder *MockGptCliAIClientMockRecorder
}

// MockGptCliAIClientMockRecorder is the mock recorder for MockGptCliAIClient.
type MockGptCliAIClientMockRecorder struct {
	mock *MockGptCliAIClient
}

// NewMockGptCliAIClient creates a new mock instance.
func NewMockGptCliAIClient(ctrl *gomock.Controller) *MockGptCliAIClient {
	mock := &MockGptCliAIClient{ctrl: ctrl}
	mock.recorder = &MockGptCliAIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGptCliAIClient) EXPECT() *MockGptCliAIClientMockRecorder {
	return m.recorder
}

// CreateChatCompletion mocks base method.
func (m *MockGptCliAIClient) CreateChatCompletion(ctx context.Context, msgs []*GptCliMessage) (*GptCliMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletion", ctx, msgs)
	ret0, _ := ret[0].(*GptCliMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletion indicates an expected call of CreateChatCompletion.
func (mr *MockGptCliAIClientMockRecorder) CreateChatCompletion(ctx, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletion", reflect.TypeOf((*MockGptCliAIClient)(nil).CreateChatCompletion), ctx, msgs)
}

// StreamChatCompletion mocks base method.
func (m *MockGptCliAIClient) StreamChatCompletion(ctx context.Context, msgs []*GptCliMessage) (*StreamResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChatCompletion", ctx, msgs)
	ret0, _ := ret[0].(*StreamResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamChatCompletion indicates an expected call of StreamChatCompletion.
func (mr *MockGptCliAIClientMockRecorder) StreamChatCompletion(ctx, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChatCompletion", reflect.TypeOf((*MockGptCliAIClient)(nil).StreamChatCompletion), ctx, msgs)
}

// SetReasoning mocks base method.
func (m *MockGptCliAIClient) SetReasoning(level laclopenai.ReasoningEffortLevel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReasoning", level)
}

// SetReasoning indicates an expected call of SetReasoning.
func (mr *MockGptCliAIClientMockRecorder) SetReasoning(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReasoning", reflect.TypeOf((*MockGptCliAIClient)(nil).SetReasoning), level)
}

// SubscribeProgress mocks base method.
func (m *MockGptCliAIClient) SubscribeProgress(invocationID string) chan ProgressEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeProgress", invocationID)
	ret0, _ := ret[0].(chan ProgressEvent)
	return ret0
}

// SubscribeProgress indicates an expected call of SubscribeProgress.
func (mr *MockGptCliAIClientMockRecorder) SubscribeProgress(invocationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeProgress", reflect.TypeOf((*MockGptCliAIClient)(nil).SubscribeProgress), invocationID)
}

// UnsubscribeProgress mocks base method.
func (m *MockGptCliAIClient) UnsubscribeProgress(ch chan ProgressEvent, invocationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubscribeProgress", ch, invocationID)
}

// UnsubscribeProgress indicates an expected call of UnsubscribeProgress.
func (mr *MockGptCliAIClientMockRecorder) UnsubscribeProgress(ch, invocationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeProgress", reflect.TypeOf((*MockGptCliAIClient)(nil).UnsubscribeProgress), ch, invocationID)
}
